# Generated by Django 5.0 on 2024-09-10 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.CharField(max_length=255)),
                ("expiry", models.CharField(max_length=255)),
                ("buy", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stop_loss", models.DecimalField(decimal_places=2, max_digits=10)),
                ("square_off", models.CharField(blank=True, max_length=255, null=True)),
                ("bull_scenario", models.CharField(max_length=255)),
                ("bear_scenario", models.CharField(max_length=255)),
                ("prediction", models.CharField(max_length=255)),
                ("actual", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TradeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIModelHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stop_loss", models.DecimalField(decimal_places=2, max_digits=10)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ai_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="adminside.aimodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aimodel",
            name="segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminside.segment"
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="type_of_trade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adminside.tradetype",
            ),
        ),
    ]
