# Generated by Django 5.0 on 2024-09-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminside", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="aimodelhistory",
            name="ai_model",
        ),
        migrations.AlterField(
            model_name="segment",
            name="name",
            field=models.CharField(
                choices=[
                    ("EQUITY", "Equity"),
                    ("FUTURES", "Futures"),
                    ("OPTIONS", "Options"),
                    ("COMMODITY", "Commodity"),
                    ("FOREX", "Forex"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tradetype",
            name="name",
            field=models.CharField(
                choices=[
                    ("INTRADAY", "Intraday"),
                    ("BTST", "BTST"),
                    ("SHORT_TERM", "Short Term"),
                    ("POSITIONAL", "Positional"),
                    ("LONG_TERM", "Long Term"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminside.segment",
                    ),
                ),
                (
                    "stock_index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminside.stockindex",
                    ),
                ),
                (
                    "trade_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminside.tradetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sl",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Stop Loss"
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminside.trade",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AIModel",
        ),
        migrations.DeleteModel(
            name="AIModelHistory",
        ),
    ]
