# Generated by Django 5.0 on 2024-09-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminside", "0002_stockindex_remove_aimodelhistory_ai_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="segment",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="trade",
            name="stock_index",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(max_length=255),
        ),
    ]
