# Generated by Django 5.0 on 2024-09-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminside", "0003_alter_trade_segment_alter_trade_stock_index_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Segment",
        ),
        migrations.DeleteModel(
            name="StockIndex",
        ),
        migrations.DeleteModel(
            name="TradeType",
        ),
        migrations.AlterField(
            model_name="trade",
            name="segment",
            field=models.CharField(
                choices=[
                    ("EQUITY", "Equity"),
                    ("FUTURES", "Futures"),
                    ("OPTIONS", "Options"),
                    ("COMMODITY", "Commodity"),
                    ("FOREX", "Forex"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(
                choices=[
                    ("INTRADAY", "Intraday"),
                    ("BTST", "BTST"),
                    ("SHORT_TERM", "Short Term"),
                    ("POSITIONAL", "Positional"),
                    ("LONG_TERM", "Long Term"),
                ],
                max_length=255,
            ),
        ),
    ]
