# Generated by Django 5.0 on 2024-09-19 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminside", "0007_orders_premium_trade_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
