# Generated by Django 5.1.1 on 2024-09-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=15, unique=True)),
                (
                    "beetle_coin",
                    models.DecimalField(
                        decimal_places=2, default=300000.0, max_digits=10
                    ),
                ),
                ("premium_details", models.TextField(blank=True, null=True)),
                ("is_premium_member", models.BooleanField(default=False)),
                ("premium_validity", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
