# Generated by Django 5.0 on 2024-09-21 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminside", "0008_trade_created_at"),
        ("user", "0002_remove_user_name_user_first_name_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="premium_details",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="premium_details",
                to="adminside.premium",
            ),
        ),
    ]
