# Generated by Django 5.0 on 2024-09-21 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminside", "0008_trade_created_at"),
        ("user", "0003_alter_user_premium_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="premium_details",
            field=models.ForeignKey(
                default="no premium selected",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="premium_details",
                to="adminside.premium",
            ),
        ),
    ]
