# Generated by Django 5.0 on 2024-09-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_premium_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="premium_details",
            field=models.CharField(blank=True, null=True),
        ),
    ]
