# Generated by Django 3.2.16 on 2024-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_premium_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
